name: Linting and Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install linters and formatters
      - name: Install linting tools
        run: |
          pip install flake8 black isort

      # Step 4: Run flake8 for linting diagnostics
      - name: Run flake8
        run: |
          flake8 gxologistics --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 gxologistics --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      # Step 5: Auto-fix formatting issues with black and isort
      - name: Auto-fix with black and isort
        run: |
          black gxologistics
          isort gxologistics

      # Step 6: Pull latest changes before committing
      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase

      # Step 7: Commit changes if auto-fixes are applied
      - name: Commit linting fixes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply linting fixes with black and isort"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
