name: Security Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Upgrade pip and setuptools
      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==75.6.0

      # Step 4: Install pip-audit and Bandit
      - name: Install security tools
        run: |
          pip install pip-audit bandit

      # Step 5: Audit Python dependencies
      - name: Run pip-audit
        working-directory: gxologistics
        run: |
          pip-audit || exit 1

      # Step 6: Static code analysis for security
      - name: Run Bandit
        working-directory: gxologistics
        run: |
          bandit -r .

      # Step 7: Ensure dependency consistency
      - name: Freeze updated dependencies
        working-directory: gxologistics
        run: |
          pip freeze > updated-requirements.txt

      # Step 8: Check for changes and optionally commit updates
      - name: Commit changes to requirements.txt
        if: success() && steps.audit-outcome.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Fix security vulnerabilities with pip-audit"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

